# Generated by slsa-autotools scan.yml
# https://github.com/lee-mcfaul2/slsa-autotools @ 44b4999e63072bafeafb8ddcc410704a4694c410
#
# Every apt package below is pinned to both an exact version
# and the SHA256 of its .deb as served by
# snapshot.ubuntu.com at 20260425T120000Z. Any drift in the
# served bytes will fail the sha256sum check at image build.
#
# This file is regenerated by scan.yml whenever it is run.
# Hand edits are preserved through the next run only if you
# re-run scan.yml yourself; otherwise a fresh run will
# overwrite. Editing individual SHA256 values is safe — the
# verification step is purely local to this file.

FROM ubuntu@sha256:5e275723f82c67e387ba9e3c24baa0abdcb268917f276a0561c97bef9450d0b4

ENV DEBIAN_FRONTEND=noninteractive

# Step 1: bootstrap ca-certificates from the default HTTP
# archive so we can reach snapshot.ubuntu.com over HTTPS.
RUN apt-get update -qq \
 && apt-get install -y --no-install-recommends ca-certificates

# Step 2: redirect apt to the pinned snapshot. All later
# apt traffic is immutable indefinitely.
RUN set -eu \
 && printf '%s\n' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260425T120000Z/ resolute main restricted universe multiverse' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260425T120000Z/ resolute-updates main restricted universe multiverse' \
    'deb https://snapshot.ubuntu.com/ubuntu/20260425T120000Z/ resolute-security main restricted universe multiverse' \
    > /etc/apt/sources.list \
 && rm -f /etc/apt/sources.list.d/*.sources /etc/apt/sources.list.d/*.list \
 && apt-get update -qq

# Step 3: download each pinned .deb, verify its SHA256,
# then install. A single RUN so failure aborts the layer
# atomically. Packages are deduplicated and sorted.
RUN set -eux \
 && mkdir -p /tmp/debs && cd /tmp/debs \
 && apt-get download \
      autoconf=2.72-3.1ubuntu2 \
      automake=1:1.18.1-3build1 \
      autotools-dev=20240727.1build1 \
      bash=5.3-2ubuntu1 \
      binutils=2.46-3ubuntu2 \
      binutils-common=2.46-3ubuntu2 \
      binutils-x86-64-linux-gnu=2.46-3ubuntu2 \
      bison=2:3.8.2+dfsg-1build4 \
      bzip2=1.0.8-6build2 \
      comerr-dev=2.1-1.47.2-3ubuntu4 \
      coreutils-from-uutils=0.0.0~ubuntu25 \
      cpp=4:15.2.0-5ubuntu1 \
      cpp-15=15.2.0-16ubuntu1 \
      cpp-15-x86-64-linux-gnu=15.2.0-16ubuntu1 \
      cpp-x86-64-linux-gnu=4:15.2.0-5ubuntu1 \
      dash=0.5.12-12ubuntu3 \
      debconf=1.5.92 \
      debianutils=5.23.2build1 \
      diffutils=1:3.12-1 \
      file=1:5.46-5build2 \
      findutils=4.10.0-3build2 \
      gawk=1:5.3.2-1ubuntu1 \
      gcc=4:15.2.0-5ubuntu1 \
      gcc-15=15.2.0-16ubuntu1 \
      gcc-15-base=15.2.0-16ubuntu1 \
      gcc-15-x86-64-linux-gnu=15.2.0-16ubuntu1 \
      gcc-16-base=16-20260322-1ubuntu1 \
      gcc-x86-64-linux-gnu=4:15.2.0-5ubuntu1 \
      gettext=0.23.2-1 \
      gettext-base=0.23.2-1 \
      git=1:2.53.0-1ubuntu1 \
      git-man=1:2.53.0-1ubuntu1 \
      gnu-coreutils=9.7-3ubuntu2 \
      grep=3.12-1 \
      gzip=1.14-1~exp2ubuntu1 \
      hostname=3.25build1 \
      krb5-multidev=1.22.1-2ubuntu4 \
      libacl1=2.3.2-2 \
      libasan8=16-20260322-1ubuntu1 \
      libatomic1=16-20260322-1ubuntu1 \
      libattr1=1:2.5.2-4 \
      libaudit-common=1:4.1.2-1build1 \
      libaudit1=1:4.1.2-1build1 \
      libbinutils=2.46-3ubuntu2 \
      libblkid1=2.41.3-3ubuntu2 \
      libbrotli-dev=1.2.0-3build1 \
      libbrotli1=1.2.0-3build1 \
      libbsd0=0.12.2-2build2 \
      libbz2-1.0=1.0.8-6build2 \
      libc-bin=2.43-2ubuntu2 \
      libc-dev-bin=2.43-2ubuntu2 \
      libc-gconv-modules-extra=2.43-2ubuntu2 \
      libc6=2.43-2ubuntu2 \
      libc6-dev=2.43-2ubuntu2 \
      libcap-ng0=0.8.5-4build5 \
      libcc1-0=16-20260322-1ubuntu1 \
      libcom-err2=1.47.2-3ubuntu4 \
      libcrypt1=1:4.5.1-1 \
      libctf-nobfd0=2.46-3ubuntu2 \
      libctf0=2.46-3ubuntu2 \
      libcurl3t64-gnutls=8.18.0-1ubuntu2 \
      libcurl4-openssl-dev=8.18.0-1ubuntu2 \
      libcurl4t64=8.18.0-1ubuntu2 \
      libdb5.3t64=5.3.28+dfsg2-10ubuntu1 \
      liberror-perl=0.17030-1 \
      libevent-2.1-7t64=2.1.12-stable-10build2 \
      libexpat1=2.7.4-1 \
      libffi8=3.5.2-4 \
      libfontenc1=1:1.1.8-1build2 \
      libfreetype6=2.14.2+dfsg-1 \
      libgcc-15-dev=15.2.0-16ubuntu1 \
      libgcc-s1=16-20260322-1ubuntu1 \
      libgdbm-compat4t64=1.26-1build1 \
      libgdbm6t64=1.26-1build1 \
      libgmp-dev=2:6.3.0+dfsg-5ubuntu2 \
      libgmp10=2:6.3.0+dfsg-5ubuntu2 \
      libgmpxx4ldbl=2:6.3.0+dfsg-5ubuntu2 \
      libgnutls-dane0t64=3.8.12-2ubuntu1 \
      libgnutls-openssl27t64=3.8.12-2ubuntu1 \
      libgnutls28-dev=3.8.12-2ubuntu1 \
      libgnutls30t64=3.8.12-2ubuntu1 \
      libgomp1=16-20260322-1ubuntu1 \
      libgprofng0=2.46-3ubuntu2 \
      libgssapi-krb5-2=1.22.1-2ubuntu4 \
      libgssrpc4t64=1.22.1-2ubuntu4 \
      libhogweed6t64=3.10.2-1 \
      libhwasan0=16-20260322-1ubuntu1 \
      libidn2-0=2.3.8-4build1 \
      libidn2-dev=2.3.8-4build1 \
      libisl23=0.27-1build1 \
      libitm1=16-20260322-1ubuntu1 \
      libjansson4=2.14-2build4 \
      libk5crypto3=1.22.1-2ubuntu4 \
      libkadm5clnt-mit12=1.22.1-2ubuntu4 \
      libkadm5srv-mit12=1.22.1-2ubuntu4 \
      libkdb5-10t64=1.22.1-2ubuntu4 \
      libkeyutils1=1.6.3-6ubuntu3 \
      libkrb5-3=1.22.1-2ubuntu4 \
      libkrb5-dev=1.22.1-2ubuntu4 \
      libkrb5support0=1.22.1-2ubuntu4 \
      libldap-common=2.6.10+dfsg-1ubuntu5 \
      libldap-dev=2.6.10+dfsg-1ubuntu5 \
      libldap2=2.6.10+dfsg-1ubuntu5 \
      liblsan0=16-20260322-1ubuntu1 \
      liblzma-dev=5.8.3-1 \
      liblzma5=5.8.3-1 \
      libmagic-mgc=1:5.46-5build2 \
      libmagic1t64=1:5.46-5build2 \
      libmd0=1.1.0-2build4 \
      libmount1=2.41.3-3ubuntu2 \
      libmpc3=1.3.1-3 \
      libmpfr6=4.2.2-3 \
      libnettle8t64=3.10.2-1 \
      libnghttp2-14=1.68.0-2 \
      libnghttp2-dev=1.68.0-2 \
      libp11-kit-dev=0.26.2-2 \
      libp11-kit0=0.26.2-2 \
      libpam-modules=1.7.0-5ubuntu3 \
      libpam-modules-bin=1.7.0-5ubuntu3 \
      libpam-runtime=1.7.0-5ubuntu3 \
      libpam0g=1.7.0-5ubuntu3 \
      libpcre2-8-0=10.46-1build1 \
      libperl5.40=5.40.1-7build1 \
      libpkgconf7=2.5.1-4 \
      libpng16-16t64=1.6.57-1 \
      libpsl-dev=0.21.2-1.1build2 \
      libpsl5t64=0.21.2-1.1build2 \
      libquadmath0=16-20260322-1ubuntu1 \
      libreadline8t64=8.3-4 \
      librtmp-dev=2.4+20151223.gitfa8646d.1-3 \
      librtmp1=2.4+20151223.gitfa8646d.1-3 \
      libsasl2-2=2.1.28+dfsg1-9ubuntu3 \
      libsasl2-modules-db=2.1.28+dfsg1-9ubuntu3 \
      libselinux1=3.9-4build1 \
      libsframe3=2.46-3ubuntu2 \
      libsmartcols1=2.41.3-3ubuntu2 \
      libssh2-1-dev=1.11.1-1build2 \
      libssh2-1t64=1.11.1-1build2 \
      libssl-dev=3.5.5-1ubuntu3 \
      libssl3t64=3.5.5-1ubuntu3 \
      libstdc++-15-dev=15.2.0-16ubuntu1 \
      libstdc++6=16-20260322-1ubuntu1 \
      libtasn1-6=4.21.0-2 \
      libtasn1-6-dev=4.21.0-2 \
      libtinfo6=6.6+20251231-1 \
      libtool=2.5.4-9 \
      libtsan2=16-20260322-1ubuntu1 \
      libubsan1=16-20260322-1ubuntu1 \
      libunbound8=1.24.2-1ubuntu2 \
      libunistring5=1.3-2build1 \
      libuuid1=2.41.3-3ubuntu2 \
      libxml2-16=2.15.2+dfsg-0.1 \
      libzstd-dev=1.5.7+dfsg-3 \
      libzstd1=1.5.7+dfsg-3 \
      linux-libc-dev=7.0.0-14.14 \
      m4=1.4.21-1 \
      make=4.4.1-3 \
      mawk=1.3.4.20260129-1 \
      nettle-dev=3.10.2-1 \
      openssl-provider-legacy=3.5.5-1ubuntu3 \
      perl=5.40.1-7build1 \
      perl-base=5.40.1-7build1 \
      perl-modules-5.40=5.40.1-7build1 \
      pkgconf=2.5.1-4 \
      pkgconf-bin=2.5.1-4 \
      readline-common=8.3-4 \
      rpcsvc-proto=1.4.3-1build1 \
      sed=4.9-2build3 \
      sysvinit-utils=3.15-5ubuntu1 \
      tar=1.35+dfsg-4 \
      util-linux=2.41.3-3ubuntu2 \
      x11-common=1:7.7+26ubuntu1 \
      xfonts-encodings=1:1.0.5-0ubuntu3 \
      xfonts-utils=1:7.7+7build1 \
      zlib1g=1:1.3.dfsg+really1.3.1-1ubuntu3 \
      zlib1g-dev=1:1.3.dfsg+really1.3.1-1ubuntu3 \
 && printf '%s\n' \
      '0014788fec9bda1a4931e71a75523ba4055eb1a626582f445a2674528a32dbc7  libnghttp2-dev_1.68.0-2_amd64.deb' \
      '0068e6a881ab327aff6c0f57357de7f397cb43302a39b10015123c1914f14d2e  libgnutls30t64_3.8.12-2ubuntu1_amd64.deb' \
      '025984be5dc70b32e02c8a668fdcceba674173bbda4a3e7ff93fac800dcdd122  debconf_1.5.92_all.deb' \
      '02ea5de2ab6ddba978606ad58647bf6371ea68c0ed63aa5d6d0d3b8c1fe77ea3  libisl23_0.27-1build1_amd64.deb' \
      '05541ea1edb19e54bea297a21a9c33d0b99ca2cfe2e86d4a67335e6640667cfc  libsframe3_2.46-3ubuntu2_amd64.deb' \
      '05a64873a18fb10d52ba2c8ee1fd0a605a974d75264d824ef2771c799f49ea63  cpp_4%3a15.2.0-5ubuntu1_amd64.deb' \
      '05c9ab6be49c5177b366b21fc1b96e042d69e2c119de898d539e55a3a778f8f7  openssl-provider-legacy_3.5.5-1ubuntu3_amd64.deb' \
      '0662549ee8b9d4fc84c60d7a3881a04b5e4e1e07947e11cdc75b34f338e4a499  libgnutls-dane0t64_3.8.12-2ubuntu1_amd64.deb' \
      '0752eddff4c494d682f433cac2f1d25196f0a405eb8c6b0b10ec46432f6fec71  libgdbm6t64_1.26-1build1_amd64.deb' \
      '079f2a9cb6215753bcc13bfea01a136fd07376fb9f8c3233efc712df40e584bd  libp11-kit-dev_0.26.2-2_amd64.deb' \
      '07bd53c587140613b3d551bdbd4a15a37002c1fe971962ab49e2c2c896cf7dda  libgmpxx4ldbl_2%3a6.3.0+dfsg-5ubuntu2_amd64.deb' \
      '11b9b2ce6702d86dd3dea60e08bd15255d7fd9545431a9e555eec47770404de0  libsasl2-2_2.1.28+dfsg1-9ubuntu3_amd64.deb' \
      '1376a5e49c8dc2ba938fadc15fce40dd01c7fbf1adf2d506a2a7cf7148e347c8  libbinutils_2.46-3ubuntu2_amd64.deb' \
      '13bb794692dbf0f7f5cdaf5df65ef822d22c8499bf1d031dd7eb9c6b0746378e  libpam-modules_1.7.0-5ubuntu3_amd64.deb' \
      '14bf36d574df2cacf2e50fa8c1f28b4b6b574b63e9561924cc942e4c9186e57e  linux-libc-dev_7.0.0-14.14_amd64.deb' \
      '1649aa71c45b047feda5b9ca303c94799bdba5befa5c9de9735cbfc59c3ef93f  cpp-15-x86-64-linux-gnu_15.2.0-16ubuntu1_amd64.deb' \
      '180b6ea0b9c07d4fd2ede79e29ee8eca830cd9384f856507e28dc24d1d3ae514  libcom-err2_1.47.2-3ubuntu4_amd64.deb' \
      '1890e37e38fd64bc10630e508f4a013a76bddbe05be2ed89e68df28463712b55  m4_1.4.21-1_amd64.deb' \
      '18b35148f64d0bb17b5c34efa6bdeefa4df9ca122ba12130f7245bccd65a950a  cpp-x86-64-linux-gnu_4%3a15.2.0-5ubuntu1_amd64.deb' \
      '18cfdce1831fb38878a9987cacd02b1a69ea7bda545f6e8eb737742defcd24b5  libpam-modules-bin_1.7.0-5ubuntu3_amd64.deb' \
      '195ca7b0ca6c91c4b4b9e17baf98b98143e3a14a0571f1613f04b318b9799510  libattr1_1%3a2.5.2-4_amd64.deb' \
      '1a443abf03a5af97f4493405e22eba52fd6935a8b0583ac32fb88b3727563e53  automake_1%3a1.18.1-3build1_all.deb' \
      '1adaaf191b33e95bc172e0cae09e4a246e22fb7dcf46a34e3e9ae66f8efbe994  diffutils_1%3a3.12-1_amd64.deb' \
      '1ae62705714f660ecdfd70273fce5b226b6cb7b9fe53776531799093edc99774  libpsl5t64_0.21.2-1.1build2_amd64.deb' \
      '1c8c808ab24ff3018ac886e3f311edee0f2d4d97d12d3908be52343e89807046  libhogweed6t64_3.10.2-1_amd64.deb' \
      '1d0610635e1fe757c8df0ec2c2cef511203c7e7bf81bbff332031c8bf87b1847  xfonts-encodings_1%3a1.0.5-0ubuntu3_all.deb' \
      '1dc986ac3cf112384919d1a339a952e8a86bede9890a4489c016fdc266a036ca  libjansson4_2.14-2build4_amd64.deb' \
      '1de7b83844537091315210afb466ff2cd022874db5a6a785ce06b41bd3507eb3  libsasl2-modules-db_2.1.28+dfsg1-9ubuntu3_amd64.deb' \
      '1f40a027bc0b31bec572baadb8d9dff7477e4fe00fa389a33a2e5f78607301b6  perl-modules-5.40_5.40.1-7build1_all.deb' \
      '1f47dbb4b688665621f5846043ab20ff00ad0859bedfea93d019a0b66978331d  libtasn1-6-dev_4.21.0-2_amd64.deb' \
      '1fab0e125d793da45d91b346c334c496776d69709a7ea78c3b34d5db6db69eab  libfontenc1_1%3a1.1.8-1build2_amd64.deb' \
      '2439c70d04fa6148b1bf3ae2b77d999d8c0906fbd540c60a2bc0463a43b7a9b3  sysvinit-utils_3.15-5ubuntu1_amd64.deb' \
      '260b3333e9f714252593b83fb31d2571097b64d337d0d7100aae7349029821fc  libreadline8t64_8.3-4_amd64.deb' \
      '281b3188840a7abdca85a02eb2609b0efad852e8994b3804a0e4227ec4ec3f90  gcc-16-base_16-20260322-1ubuntu1_amd64.deb' \
      '28da225c111d3ce9d230209cca24db46ec645f631f593f188bef718d8a1e4711  gcc-15_15.2.0-16ubuntu1_amd64.deb' \
      '2fb4d81c14fdf34251639ae82f5181f9f98480ea16125d535571ac1be9db3065  libgcc-s1_16-20260322-1ubuntu1_amd64.deb' \
      '3264ec3ed617abec65c55f2e165cf78f8c9dd006859faf0d863a8bc6095a67fd  libmagic-mgc_1%3a5.46-5build2_amd64.deb' \
      '32fa5bde1891f46fd4f422e466c863fb78e834b634e1aa08211c8eea68870af5  libgcc-15-dev_15.2.0-16ubuntu1_amd64.deb' \
      '34365d611ccf1f717f90a92fbe52ed96ae1829ab9be363c68a83563322797f8f  libzstd1_1.5.7+dfsg-3_amd64.deb' \
      '34b1757ce619720541c7e1e8d8f3aa506cb327731374e284ffb6ec872a2c566f  libctf0_2.46-3ubuntu2_amd64.deb' \
      '353f622f6432a3d65bedd3c23e0af98c2c438650b497b355772a56a05ebf7dd0  libpkgconf7_2.5.1-4_amd64.deb' \
      '387910c6d79c39c47d83ca729b84c0d30c674a340e3b290ec7b6df3288c19f9a  libbz2-1.0_1.0.8-6build2_amd64.deb' \
      '38ad8500817a9159db210fecfb8c50fa82d7a8829730fcdf8ae60e3523676d41  liblzma5_5.8.3-1_amd64.deb' \
      '3c846f001d87b16e5038a3919ca975276808a2db17459308a9d0f965c1cddac5  binutils-common_2.46-3ubuntu2_amd64.deb' \
      '3ce3aea44b2ec00780c48b1b8e1f7e672166ec3ccac14b0eae8890e55983061e  libselinux1_3.9-4build1_amd64.deb' \
      '3e116766f1a7b149994d4745556023d993d26401223d1595520a991d4ba737fb  libpcre2-8-0_10.46-1build1_amd64.deb' \
      '3f8edc884ebb8c55120cb0535fb4e1029651d97fd380936ec5211bb4c926d809  perl-base_5.40.1-7build1_amd64.deb' \
      '3fff865e0ac12c9a1e1da0a2ba42a9a2f3daa909b51ec859a3a6815f3d8d24ab  libbrotli-dev_1.2.0-3build1_amd64.deb' \
      '41f3cecf36e5e82fc7d86f93611306b49c5ff4ab947cd574b0a8787faedf4fed  util-linux_2.41.3-3ubuntu2_amd64.deb' \
      '420e777fef436f397a85ddedde53fbb44f92c7ca8e87d581f9d86573859e1aa4  libquadmath0_16-20260322-1ubuntu1_amd64.deb' \
      '42705a701a98d84c203c6f96f08c6fd6a29a1ef978683e1ffbf0e27535b20ddb  libtinfo6_6.6+20251231-1_amd64.deb' \
      '434394dc6703f8e195c19764bd03aa55a0a9986749285fd7abe0a0e4ab086cfc  autotools-dev_20240727.1build1_all.deb' \
      '4755b21ef0f3c04a9b7544d31341e8fbf3e835817e7b65e5f1b7e17b855c3c43  liblzma-dev_5.8.3-1_amd64.deb' \
      '484ac5fd30a19bfade8db336fe70f3c046beccd1c9a9ac327fcd89d29dd5a125  libcc1-0_16-20260322-1ubuntu1_amd64.deb' \
      '4a7423124bbd459c0aa38b7389ec7802fa6899654767a95fc27de70967fedd48  libffi8_3.5.2-4_amd64.deb' \
      '4aba1f758114185fbaa798acfd4570492a5ce0ff906d36998544a68b361c785f  libldap-dev_2.6.10+dfsg-1ubuntu5_amd64.deb' \
      '4e066f8382f775d6600eee715add8fdc8da5ea8f0cf7b0f715aba38c8d57d64f  tar_1.35+dfsg-4_amd64.deb' \
      '52cc67a0a52735fe72b1d02ccf47b8b0b7533971a541b0ac289ad91bec548d8d  libgnutls-openssl27t64_3.8.12-2ubuntu1_amd64.deb' \
      '53cdc5a963bbdda938f8996496a5e78bcf484e6e41a2ef2c0f8cf566808f71f5  readline-common_8.3-4_all.deb' \
      '546d6b0c2b2f5c61494ee5d11aa1b49476213af27a66edd9e05bb3ef00940557  findutils_4.10.0-3build2_amd64.deb' \
      '563091a9b615a5a59951c2cc4478163d099df366a051113e8ce5bb2baab7f0c8  dash_0.5.12-12ubuntu3_amd64.deb' \
      '57ab343c3dd28ce7101dc4e23de4e9d5bd3e58c6cb0ecd5ba0c42a877fc8868a  libcrypt1_1%3a4.5.1-1_amd64.deb' \
      '59c74951324ead0ff77ab945d561feb1b21bc189b793600b8e2b7cf4d39b1ee5  libtasn1-6_4.21.0-2_amd64.deb' \
      '5a1a4cd407a868e766626f551646b00880fc1534db5e6d47208310a17252f306  gettext-base_0.23.2-1_amd64.deb' \
      '5a302d705d562fb7e150415b00651c00fed58b633faadff0b332eac1b73fadb3  gcc-15-base_15.2.0-16ubuntu1_amd64.deb' \
      '5acad718e7fe39a7407d87402112a3bac97948723e5ea058c5996e32e8ceeb1e  libkadm5srv-mit12_1.22.1-2ubuntu4_amd64.deb' \
      '5b3146cd9d380e4725fc5b5e54795ae1f72d165d93e68ce29076b69762661fd4  libtool_2.5.4-9_all.deb' \
      '5ca038ae110ddf65e190b9fe88822592abd45cecba5001f3e4ce7692ca1f31be  libctf-nobfd0_2.46-3ubuntu2_amd64.deb' \
      '601b9f92a04ea9ff7de6f60f60c34f2e2743f9c478125ac9e413f29a1fa728d9  zlib1g-dev_1%3a1.3.dfsg+really1.3.1-1ubuntu3_amd64.deb' \
      '60b7a5982b477e10b9f11e2278289135f79e9dc75a312575778b21a0a631bea5  x11-common_1%3a7.7+26ubuntu1_all.deb' \
      '62019928a6baeaba8d12d2d4cb7c1e4c9a9550a1eb4541b8de0cacfeae1d09e3  libbsd0_0.12.2-2build2_amd64.deb' \
      '62524c67075889b68fa441851604ee7f801f89d0b9a20bc9db55f52561a7cb3b  libpsl-dev_0.21.2-1.1build2_amd64.deb' \
      '62a09e8a10b1b7704dace298fd2a0e65e414890297497d5b4ac1a96891b3dd6f  libidn2-dev_2.3.8-4build1_amd64.deb' \
      '63ece6297e34148e2cad22968059b7ac4e631b0ce2aaffa8424774fa2e02dacf  libssh2-1t64_1.11.1-1build2_amd64.deb' \
      '67292d559b11f0fc8d63d97a352e3aa3710744fee0f478fc6a695723ca64eb6b  libkdb5-10t64_1.22.1-2ubuntu4_amd64.deb' \
      '6b066ab912300b2c6a965a9a8045da45c237a52b76c2c11d8f2ceaf7aabfacbb  libgprofng0_2.46-3ubuntu2_amd64.deb' \
      '6b5b60a5c372b6e9d1dcfa1507317aae59bf809d4f4d6d363d3ef0a58a189137  gnu-coreutils_9.7-3ubuntu2_amd64.deb' \
      '6bd25c936289463c6472290d3b4377edf8dd4f5e3a07f356fb0adf2de04a8055  libhwasan0_16-20260322-1ubuntu1_amd64.deb' \
      '6c8def1cafec89468fef8bd0d7a4eb66192a7850bf17c9decf7bca8fcf3dd5fa  libc6-dev_2.43-2ubuntu2_amd64.deb' \
      '6d81369284ba3fd094f635fe6b9f8dfc71baaca36c1f758fe62244839e25ecf0  libzstd-dev_1.5.7+dfsg-3_amd64.deb' \
      '6fb2dd68379bf9578af5ead58203ab322e3b1cf3a6f9562a1e4d12c18e923bfc  gettext_0.23.2-1_amd64.deb' \
      '707572352c05ef47816d4abe1c299172d29b22c096eb6cd56494997223f79b99  comerr-dev_2.1-1.47.2-3ubuntu4_amd64.deb' \
      '7393f33be5584941bcfbd03a25901058c708046ee5dded01c21d56652a2d0eb7  gcc-x86-64-linux-gnu_4%3a15.2.0-5ubuntu1_amd64.deb' \
      '74091083c33728c7a60bc95025bcad00569164cad7424bb2294b34361886d5a9  krb5-multidev_1.22.1-2ubuntu4_amd64.deb' \
      '74defa71b7f81d66b103afccfce750ad356976696b40c96c846ddc956fcfe937  libmpfr6_4.2.2-3_amd64.deb' \
      '7562e7f3c551b2e005d71c5c20c5f34fa9d7926bf93e7eae4ab0a9f0ab061232  libperl5.40_5.40.1-7build1_amd64.deb' \
      '763a89b5c40942860f4d000499579763a2123c1226b3d2a66677846aa304a85d  libaudit-common_1%3a4.1.2-1build1_all.deb' \
      '763fa3325cb0cb5dff197ddfce2671da824c8af9ddb98a585c1fad0419870124  bzip2_1.0.8-6build2_amd64.deb' \
      '76e64dda8fcbc3c04437085b01b0761552d9b4e7e90817aa56d478b275619736  gawk_1%3a5.3.2-1ubuntu1_amd64.deb' \
      '77cbd0ddf7e7487079ec300ff7751322de5e7d67f0f46749591b78ff1442cbe8  librtmp1_2.4+20151223.gitfa8646d.1-3_amd64.deb' \
      '77f8d49c031182bbd6c4fe4ec9ad49edb5d4607f2dac795fc6932dce0e8f541e  libacl1_2.3.2-2_amd64.deb' \
      '7a9d4ce17f45d687ed38758bdc79efc8b5c7d79987dc5298de25961691b6bd09  bison_2%3a3.8.2+dfsg-1build4_amd64.deb' \
      '823df284bbc343ae6e22d69dc14a39c31b6c81fc2bccdd9ed720b88af92fcfa4  libdb5.3t64_5.3.28+dfsg2-10ubuntu1_amd64.deb' \
      '82d4aba3490578089d399921bf6444ad848468a23f2cb37262625b28e3615a76  bash_5.3-2ubuntu1_amd64.deb' \
      '82fa61135e7154d7958feaa91ec1808a688eb1e0e06822ab35e99e2480feb148  libatomic1_16-20260322-1ubuntu1_amd64.deb' \
      '83a2a924c11759a2ed6e6f98f456d28e1b026974ce9e6e7ef12c9ac43b2d543e  libnettle8t64_3.10.2-1_amd64.deb' \
      '855e4f4a543789a427ad9aef77a31fbf99aebdd33576caa467e67a4301cd2d20  libmagic1t64_1%3a5.46-5build2_amd64.deb' \
      '858242571fc2585c1f8eb83ae01d020f0f4a92679d0de8fe31146f6687bdd84a  libbrotli1_1.2.0-3build1_amd64.deb' \
      '858a1ddd299cff3932bcc7085d16535f5b5140d15f6d84bd1b94b4a2a6c456b2  libcurl4t64_8.18.0-1ubuntu2_amd64.deb' \
      '85ffc97dcc6c63c80693b07a984128b9e267992482f12e1c0dd87c65f014c769  libc-dev-bin_2.43-2ubuntu2_amd64.deb' \
      '866fd07f5d3367fa42f1b0957007478b110f30918c08bedff566a2d6217bc3da  libcurl3t64-gnutls_8.18.0-1ubuntu2_amd64.deb' \
      '88c0163f1acb384abde07641b7e13fcaea36e0a3b88fc57a653779fc429fc46a  libunistring5_1.3-2build1_amd64.deb' \
      '8b59e0e881059cecebdbcdc6846f6626196c6085a476da8acde6f05e26661b02  libkadm5clnt-mit12_1.22.1-2ubuntu4_amd64.deb' \
      '8c14223ae11b2bba96afa0a1a08206cc63ad220d999e90a119f7c76549c62e16  libevent-2.1-7t64_2.1.12-stable-10build2_amd64.deb' \
      '8d3a361e8655a0ff4a390243059949fa6f22d42d0e266f58b57c124eb21d2993  libldap2_2.6.10+dfsg-1ubuntu5_amd64.deb' \
      '8d996790c80f2ece3f8885708e051966b3e6e427f919bf259e3282e1f7286041  nettle-dev_3.10.2-1_amd64.deb' \
      '919b209f5040c1dca1d9c3912521e4bc476028c2e16905ab09347004a599a722  libldap-common_2.6.10+dfsg-1ubuntu5_all.deb' \
      '91fa094c31783f7ccf0f0df8ed06447655c40476ba61fc95dbd245a313f8171e  binutils-x86-64-linux-gnu_2.46-3ubuntu2_amd64.deb' \
      '9277da0b7f23a1611270a8e10b3132553aa20fc80202e1bd7e0ab30d2c3aafb7  sed_4.9-2build3_amd64.deb' \
      '92bdac0f443a648859d06dee3defb9c96864fd76df6cfe617ca70bb261344767  libidn2-0_2.3.8-4build1_amd64.deb' \
      '95b7a9b63096840cb960562d190a802a541055366eb4bc756c763d7de6e174d8  libtsan2_16-20260322-1ubuntu1_amd64.deb' \
      '968b0e503f877a81c67bf82b634973e73901f6c4f4c741b5ec09824120791cd3  file_1%3a5.46-5build2_amd64.deb' \
      '9690471f395b6652f2cd8962334b9400e26a10daf4af7bf2f2c1a0325c193f0b  pkgconf-bin_2.5.1-4_amd64.deb' \
      '97e8c7ce05e09ea5b766c99f4d77e20cb70db61396c2e83bb43715c6e2f0ac1e  xfonts-utils_1%3a7.7+7build1_amd64.deb' \
      '9a400597b1db45cf51238c9eb556e211ec092d363cfb7ebebac627750ba56433  libstdc++-15-dev_15.2.0-16ubuntu1_amd64.deb' \
      '9b071ec8637a7d87e152eee7952df8f3374e432bafecd3bcc30948feb3acb3e9  mawk_1.3.4.20260129-1_amd64.deb' \
      '9d23ccd2a24d8618ca8bc7f1e14e1d02b9632854d69c82b6f8753dc5c1a98b16  pkgconf_2.5.1-4_amd64.deb' \
      '9edd0db0fa94580ab013529d6842a8e89b8ed22ab337da5e95cbb43971978815  autoconf_2.72-3.1ubuntu2_all.deb' \
      '9f921930903e1dfa626593a411dba2146c91cdacce724f541a079b181452ef41  libpam-runtime_1.7.0-5ubuntu3_all.deb' \
      'a0d9a3f3caa5d924622f31ca24f64a13526785f67ef4453c41dc8a24afeb19dc  libunbound8_1.24.2-1ubuntu2_amd64.deb' \
      'a30fdde4eff9088eb91050856b58b7a87abc668a1d88895a9ee670c76f091cb0  libsmartcols1_2.41.3-3ubuntu2_amd64.deb' \
      'a32b9ad585e39bdc7bd15d1eae6293461e6d466859a1dd2f7862d1e40f89b9d8  libstdc++6_16-20260322-1ubuntu1_amd64.deb' \
      'a76ad9102039122ef72b01c9c364e7d8967331414cbe19151c01d1391ff9fe25  libfreetype6_2.14.2+dfsg-1_amd64.deb' \
      'a86f39d57a32b7c919c0ad721fc2f17ab533a42fda348c8d81a4eea1577a014f  make_4.4.1-3_amd64.deb' \
      'a95109fde453f2c43027b6babfb395f2e037c65b901aa69aaaef5e3067b0b93e  libcurl4-openssl-dev_8.18.0-1ubuntu2_amd64.deb' \
      'a95c75b486f26fe8b140a632fd9e2883b7e2efc21f7586e155d27d2d2ff0ddc0  libmpc3_1.3.1-3_amd64.deb' \
      'a9bbe9d4a4bcd5875bbd0f53e67c379bc881d1c1a80522d51dfb4b107cc31819  libgmp10_2%3a6.3.0+dfsg-5ubuntu2_amd64.deb' \
      'aab1f05de965b5f45af845ef45e276bcf53d811804633728bf540c58391a8bd3  libgnutls28-dev_3.8.12-2ubuntu1_amd64.deb' \
      'acf0babd7e2da02a1f03981398624f7ad4660eb1ff188b4c9e93a350f98d02cd  libpam0g_1.7.0-5ubuntu3_amd64.deb' \
      'add19738c63794d2aa9ac529d3b8aebe2e88980faecb6c1c59f07aefd6c3c314  libgomp1_16-20260322-1ubuntu1_amd64.deb' \
      'b1def6b47f4f45852e4f79127fad9b947e2b9c1d5e2282e986b8bdb0ddd51b24  perl_5.40.1-7build1_amd64.deb' \
      'b2d8c9534c882635737371984a4beec5275c8431d9022c7b6ecbe6d0a4af73b2  libssl-dev_3.5.5-1ubuntu3_amd64.deb' \
      'b43e38f2d5ae4aa38471e1b3f90ed63e96c2ce614ffe496cdcd72f9944e87a4a  libgmp-dev_2%3a6.3.0+dfsg-5ubuntu2_amd64.deb' \
      'b96f99f7964c0768c4f421b5aab71d03a25a749695c4058ff0304a101fcf1870  gzip_1.14-1~exp2ubuntu1_amd64.deb' \
      'baacc9086e17c8cadc3603365e660f907bca483de4446e56e6f1bc25da4c02be  cpp-15_15.2.0-16ubuntu1_amd64.deb' \
      'bcba1775a914698ba5270f0febb1c47a3fceede86b17c574550d84e0b581dc0f  libkrb5-3_1.22.1-2ubuntu4_amd64.deb' \
      'c0bd8dbe186941f2aaf2b1536d1b48084a7ceda68369afb7f66391b9bcacba36  libmount1_2.41.3-3ubuntu2_amd64.deb' \
      'c13775dc0c984403f3fcad229d14507a9f387763bd07ace1e5f93897ee6b8434  libc6_2.43-2ubuntu2_amd64.deb' \
      'c34230e6892fa95e498e51640f7131946120b83eb672f586e341fa53bf504359  libc-bin_2.43-2ubuntu2_amd64.deb' \
      'c3b36d7357dea773eefe6c4f97ebff416e5afee22489dc1f729e31d6f47872e9  git_1%3a2.53.0-1ubuntu1_amd64.deb' \
      'c45bbbf9c87457d90b8ba38720c5f01b9388c380d40f303c26f5c4953932da26  zlib1g_1%3a1.3.dfsg+really1.3.1-1ubuntu3_amd64.deb' \
      'c90895d3b6cd164fcb54def68c7dff74419f869c837fa607e3f54c1a0e742263  liblsan0_16-20260322-1ubuntu1_amd64.deb' \
      'cb85c869fe056e9e466efcfa3403408b0a87db1da1cafa585140a9be59fe58a1  liberror-perl_0.17030-1_all.deb' \
      'cc2870c52d3d6845bd792e861930dd6afc5fe165edb0c8c3700332c3bfbd666e  git-man_1%3a2.53.0-1ubuntu1_all.deb' \
      'cde09806b1b60d0ab8ab96033177cb21a0290333a946f25572de8f72b4403695  libubsan1_16-20260322-1ubuntu1_amd64.deb' \
      'd14fc7bf644b495083f77c99ff168f1a2215c8b3b7ad5202e0345dc1092002b0  binutils_2.46-3ubuntu2_amd64.deb' \
      'd2328ad5c97b9df2decbfdcd3a849cbf38f6c823aa96eef7fe2143b791aac96f  libnghttp2-14_1.68.0-2_amd64.deb' \
      'd3b8aa4efc9851ad9641ef2b1cc13d125c7c45d167e53527c694255d0c47b68f  libaudit1_1%3a4.1.2-1build1_amd64.deb' \
      'd59b3a851c0b58759e9f940fa407f68a6ef46401381e5389c74e5ded5419262d  libasan8_16-20260322-1ubuntu1_amd64.deb' \
      'd7102b9d3fd35fd7a66d94ba0765a9c8e87b2b80e3633ef4af401dd0c952bafd  rpcsvc-proto_1.4.3-1build1_amd64.deb' \
      'd780844418b745c432a5d6c85f055625f37e27523b026baee0c87d386a0aab0a  gcc_4%3a15.2.0-5ubuntu1_amd64.deb' \
      'da684bb562e167721ae38366586aaee0b4cc580b9ee6d0220128b15ef9c5be75  libmd0_1.1.0-2build4_amd64.deb' \
      'dca245ac780cbdd61d6a8b148b2f582ef2f4d051c42978925d6a9d32730fe338  libkrb5-dev_1.22.1-2ubuntu4_amd64.deb' \
      'df0e5375c9e981b18e396c2e9ec1e359f226576a9b94a311bf07603f3ca6023a  gcc-15-x86-64-linux-gnu_15.2.0-16ubuntu1_amd64.deb' \
      'e3af297b2131aea35eab7e2751b4158ec7ae4ffb6d746043199f766fc727744f  libpng16-16t64_1.6.57-1_amd64.deb' \
      'e70d3422e24b267293215134458f340944bf10e92b27147594c69a7dd2823089  libp11-kit0_0.26.2-2_amd64.deb' \
      'e9329ba8c8c92b6cb10e3adf8bb75ed6289ada8e4f395550b3f1dc84f251f7ac  libgssapi-krb5-2_1.22.1-2ubuntu4_amd64.deb' \
      'e9ef750cc8ba426dee52f56aba0150e7e463b2658173bed8c4ca2927eec1c447  libgdbm-compat4t64_1.26-1build1_amd64.deb' \
      'ea7d3cc642ffe2459c35a85c894f80e92499b9eba13bdcb225e0aa751c0970be  libkeyutils1_1.6.3-6ubuntu3_amd64.deb' \
      'ea9d94da2fb6564391145f3a9630c140c8dd771a38ae753983e8dc55cc22e102  libuuid1_2.41.3-3ubuntu2_amd64.deb' \
      'eb155f0a9531b5f3b1c06e0e415c4cd7e01777e7714cf51ac094fa6afa01638f  debianutils_5.23.2build1_amd64.deb' \
      'eb5ba6fd4ec1a68801e757f4492c6c6b30119ff277ac9d99629a011559c963f0  libc-gconv-modules-extra_2.43-2ubuntu2_amd64.deb' \
      'ed00525d45980e5514b683b2e9d54293ed8e685d132dcdb3af9ad343000d77a0  librtmp-dev_2.4+20151223.gitfa8646d.1-3_amd64.deb' \
      'ef20434fbf03076d238155e937870cf389884ae81bd8c3569ff6043aef6da398  libcap-ng0_0.8.5-4build5_amd64.deb' \
      'ef78089497946219cac03209d951bbfff93480104e791b770a7bf6429452e475  libexpat1_2.7.4-1_amd64.deb' \
      'ef841c269b5e9f324e38b1069f712a13c29237051f037847d1de79441dc3a9a2  libitm1_16-20260322-1ubuntu1_amd64.deb' \
      'f0243e2370cf86578de2659b4d1f57f81c2f9e7401dd13d183d51f60b139c1d2  libssh2-1-dev_1.11.1-1build2_amd64.deb' \
      'f0c87cee9a1fb871e66698dc05fe38e0a3e7232eb961b690a8e7dc26f9753813  libxml2-16_2.15.2+dfsg-0.1_amd64.deb' \
      'f2caf1f807c0b203e5f4545c3010ac34b2dd5f546704e5b1b9c62a41d483771e  libblkid1_2.41.3-3ubuntu2_amd64.deb' \
      'f8a985e1bc63f943db0ca9ada3309edfda4042a3023e36d80c6cf3e9591c557b  libk5crypto3_1.22.1-2ubuntu4_amd64.deb' \
      'f9cfb4ba27d0745cbfc7c064cc68f15ea3d6b144a4fd1da9c5f83fe30008aef7  libkrb5support0_1.22.1-2ubuntu4_amd64.deb' \
      'f9fdae226c125571bcee451a43ec62d895c996fb8b02e9c24e651f540ae34340  libgssrpc4t64_1.22.1-2ubuntu4_amd64.deb' \
      'fc23170281e0455ab02ab8b0041eac4b3f46a3ae9df165c117999260ccbc093a  grep_3.12-1_amd64.deb' \
      'fd89943a93fdb3e2746faff8fe1bb23106dbdd6c891df0f50fe2f8b42d6f089d  coreutils-from-uutils_0.0.0~ubuntu25_all.deb' \
      'fdae0a5b58249fc43cd705eb6e8e20bb1e8af7dbb1fa3a90e90eb091218c5a28  hostname_3.25build1_amd64.deb' \
      'fe78b8124fb6c8c0d7efc8f2bd8d5e0d3f217351f520a3b4652ee0afe24143c2  libssl3t64_3.5.5-1ubuntu3_amd64.deb' \
    > SHA256SUMS \
 && sha256sum -c SHA256SUMS \
 && apt-get install -y --no-install-recommends ./*.deb \
 && cd / && rm -rf /tmp/debs \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# Re-register the workspace as a safe git directory for
# the container user. Needed for any later git operation
# this image's consumers may want to do.
RUN git config --global --add safe.directory '*'
